### ISSUE TITLE
Название переменных

### ISSUE THREAD

**Issue by iruslanjafarov** [orion787/SomeCPP#1]
Убирай названия cringe
![image](https://github.com/user-attachments/assets/1053f94d-2f4c-4e0c-a98e-5d739104aad1)

**Comment by orion787** [comment]
Спокуха, это в тестах для библиотеки кринж. В основном коде библиотеки нет никаких переменных с кринжовыми названиями

**Comment by iruslanjafarov** [comment]
базар
